apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: kamaji-etcd
    git:
      url: https://github.com/clastix/kamaji-etcd
      ref: v0.17.0
    includePaths:
    - charts/kamaji-etcd/**/*
    newRootPath: charts/kamaji-etcd
- path: helm/kamaji-etcd
  contents:
  - path: .
    directory:
      path: vendor/kamaji-etcd
